# Generated by Django 5.2.17 on 2026-10-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_content_hash_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobad",
            name="source_url",
            field=models.URLField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
