# Generated by Django 5.2.17 on 2026-10-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_source_url_not_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobad",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobad",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobad",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual_paste", "manual_paste"),
                    ("jobtech_api", "jobtech_api"),
                ],
                default="manual_paste",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobad",
            name="source_external_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="jobad",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_external_id__isnull", False)),
                fields=("source", "source_external_id"),
                name="unique_external_id_per_source",
            ),
        ),
    ]
